### ISSUE TITLE
proper library layout

### ISSUE THREAD

**Issue by BaerLKR** [Abdur-rahmaanJ/richterm#11]
Hello,
it would be useful for users if the project was layed out like a library and not a bin package.
The `main.rs` would then live in the `examples` dir.

**Comment by Abdur-rahmaanJ** [comment]
@BaerLKR I am new to Rust. If you could send a PR that would be useful. I even struggled how to run a project. 
If ever you don't get the time, i'll eventually do it, but, it'd be nice to have some experienced touches around ^^.

**Comment by BaerLKR** [comment]
I am not experienced at all but i'd love to do it. I am on vacation for the next 2 weeks tho, so it couod take a while but i can make a pr when i am home

**Comment by BaerLKR** [comment]
I recommend you read chapter 14 of the rust book (https://doc.rust-lang.org/stable/book/ch14-00-more-about-cargo.html) and try to change it yourself (it is not a big change)

**Comment by Abdur-rahmaanJ** [comment]
Cool! Do contribute when you are back ^^ and thanks for the link!

**Comment by Abdur-rahmaanJ** [comment]
Solved with #18
